-- CAREERLIFT JOB PORTAL
-- Run this in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text,
  category text,
  location text,
  qualification text,
  experience text,
  salary text,
  last_date text,
  description text,
  apply_url text not null,
  telegram_url text,
  whatsapp_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.jobs enable row level security;

-- Helper function used by policies. It checks the logged-in user's profile.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  );
$$;

-- Public visitors can read jobs.
drop policy if exists "Public can read jobs" on public.jobs;
create policy "Public can read jobs"
on public.jobs for select
to anon, authenticated
using (true);

-- Only admins can add jobs.
drop policy if exists "Admins can insert jobs" on public.jobs;
create policy "Admins can insert jobs"
on public.jobs for insert
to authenticated
with check (public.is_admin() and created_by = auth.uid());

-- Only admins can edit jobs.
drop policy if exists "Admins can update jobs" on public.jobs;
create policy "Admins can update jobs"
on public.jobs for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Only admins can delete jobs.
drop policy if exists "Admins can delete jobs" on public.jobs;
create policy "Admins can delete jobs"
on public.jobs for delete
to authenticated
using (public.is_admin());

-- A user can read only their own profile row.
drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
to authenticated
using (id = auth.uid());

-- OPTIONAL: create the first admin:
-- 1. Create a user in Supabase Dashboard > Authentication > Users.
-- 2. Copy that user's UUID.
-- 3. Run:
-- insert into public.profiles (id, is_admin)
-- values ('PASTE-USER-UUID-HERE', true)
-- on conflict (id) do update set is_admin = true;
