-- CAREERLIFT JOB PORTAL
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text,
  category text,
  location text,
  qualification text,
  experience text,
  salary text,
  last_date text,
  description text,
  apply_url text not null,
  telegram_url text,
  whatsapp_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.jobs enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  );
$$;

-- JOB POLICIES
drop policy if exists "Public can read jobs" on public.jobs;
create policy "Public can read jobs" on public.jobs for select to anon, authenticated using (true);

drop policy if exists "Admins can insert jobs" on public.jobs;
create policy "Admins can insert jobs" on public.jobs for insert to authenticated with check (public.is_admin() and created_by = auth.uid());

drop policy if exists "Admins can update jobs" on public.jobs;
create policy "Admins can update jobs" on public.jobs for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can delete jobs" on public.jobs;
create policy "Admins can delete jobs" on public.jobs for delete to authenticated using (public.is_admin());

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles for select to authenticated using (id = auth.uid());

-- RESOURCE HUB
create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  type text,
  resource_url text not null,
  image_url text,
  description text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.resources enable row level security;

drop policy if exists "Public can read resources" on public.resources;
create policy "Public can read resources" on public.resources for select to anon, authenticated using (true);

drop policy if exists "Admins can insert resources" on public.resources;
create policy "Admins can insert resources" on public.resources for insert to authenticated with check (public.is_admin() and created_by = auth.uid());

drop policy if exists "Admins can update resources" on public.resources;
create policy "Admins can update resources" on public.resources for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can delete resources" on public.resources;
create policy "Admins can delete resources" on public.resources for delete to authenticated using (public.is_admin());

-- PUBLIC CONTACT PROFILE
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  phone text,
  email text,
  telegram_url text,
  whatsapp_url text,
  is_active boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.contacts enable row level security;

drop policy if exists "Public can read active contacts" on public.contacts;
create policy "Public can read active contacts" on public.contacts for select to anon, authenticated using (is_active = true or public.is_admin());

drop policy if exists "Admins can insert contacts" on public.contacts;
create policy "Admins can insert contacts" on public.contacts for insert to authenticated with check (public.is_admin() and created_by = auth.uid());

drop policy if exists "Admins can update contacts" on public.contacts;
create policy "Admins can update contacts" on public.contacts for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can delete contacts" on public.contacts;
create policy "Admins can delete contacts" on public.contacts for delete to authenticated using (public.is_admin());

-- =========================================================
-- SUPABASE STORAGE: RESOURCE FILE UPLOADS
-- =========================================================
-- Creates a public bucket named "resources" for PDFs and images.
-- The admin portal uploads directly into this bucket.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'resources',
  'resources',
  true,
  20971520,
  array['application/pdf','image/jpeg','image/png','image/webp']
)
on conflict (id) do update
set public = true,
    file_size_limit = 20971520,
    allowed_mime_types = array['application/pdf','image/jpeg','image/png','image/webp'];

-- Anyone can view files because the bucket is public.
drop policy if exists "Public can view resource files" on storage.objects;
create policy "Public can view resource files"
on storage.objects for select
to public
using (bucket_id = 'resources');

-- Only CAREERLIFT admins can upload files.
drop policy if exists "Admins can upload resource files" on storage.objects;
create policy "Admins can upload resource files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'resources' and public.is_admin());

-- Only CAREERLIFT admins can delete files.
drop policy if exists "Admins can delete resource files" on storage.objects;
create policy "Admins can delete resource files"
on storage.objects for delete
to authenticated
using (bucket_id = 'resources' and public.is_admin());

-- OPTIONAL: create your first admin.
-- 1. Create a user in Supabase Dashboard > Authentication > Users.
-- 2. Copy the user's UUID.
-- 3. Run:
-- insert into public.profiles (id, is_admin)
-- values ('PASTE-USER-UUID-HERE', true)
-- on conflict (id) do update set is_admin = true;
